### ISSUE TITLE
USER STORY: Project Set up

### ISSUE THREAD

**Issue by panzek** [panzek/portfolio4-cuisine-plus#11]
# Process:

- [ ] Create and activate Virtual Environments
- [ ] Install Django and the supporting libraries
     - [ ] gunicorn
     - [ ] Install supporting libraries needed for PostgreSQL
     - [ ] dj_database_url 
     - [ ] psycopg2
- [ ] Install Cloudinary
- [ ] Create Environment Variables to hide sensitive data 
    - [ ] env.py
